version: '3'
services:

    front.admin:
        image: prostaff.azurecr.io/front.admin:latest
        volumes:
            - ./front/admin:/usr/src/app
        command: sh -c " npm install && npm start "
        networks:
            - diplom
        environment:
            - NAME=front.admin
        env_file:
            - .env

    db.mysql.main:
        image: prostaff.azurecr.io/db.mysql.main:latest
        volumes:
            - './volumes/db/mysql/main:/var/lib/mysql'
        networks:
            - diplom
        env_file:
            - .env

    storage.minio:
        image: prostaff.azurecr.io/storage.minio
        ports:
            - "443:9000"
        volumes:
            - ./volumes/storages/minio:/data
            - ./certbot/conf/live/househub.pp.ua/fullchain.pem:/etc/ssl/certs/public.crt
            - ./certbot/conf/live/househub.pp.ua/privkey.pem:/etc/ssl/certs/private.key
        networks:
            - diplom
        env_file:
            - .env

    laravel.jobs:
        image: prostaff.azurecr.io/laravel.jobs:latest
        volumes:
            - './back/laravel:/var/www/html'
        command: sh -c "/var/www/html/artisan queue:work"
        networks:
            - diplom
        environment:
            - NAME=jobs.laravel
        depends_on:
            - laravel.api
        env_file:
            - ./back/laravel/.env

    front.docs:
        image: prostaff.azurecr.io/front.docs:latest
        volumes:
            - ./docs:/usr/share/nginx/html/docs
        ports:
            - "8080:8080"
        networks:
            - diplom
        env_file:
            -   ./docs/doc.env

    redis.socket:
        image: prostaff.azurecr.io/redis.socket:latest
        volumes:
            - './volumes/db/redis/sockets:/data'
        networks:
            - diplom 

    socket.jonny:
        image: prostaff.azurecr.io/socket.jonny:latest
        volumes:
            - ./socket/socket_instance:/usr/src/app
        command: sh -c " npm install && npm start "
        networks:
            - diplom
        depends_on:
            - redis.socket
        environment:
            - SERVER_NAME=socket.jonny
        env_file:
            - .env

    front.public:
        image: prostaff.azurecr.io/front.public:latest
        volumes:
            - ./front/public:/usr/src/app
        command: sh -c " npm install && npm start "
        networks:
            - diplom
        environment:
            - NAME=front.public
        env_file:
            - .env

    laravel.api:
        image: prostaff.azurecr.io/laravel.api:latest
        volumes:
            - './back/laravel:/var/www/html'
        command: sh -c "composer install && /var/www/html/artisan serve --host=0.0.0.0"
        networks:
            - diplom
        environment:
            - NAME=laravel.api      
        env_file:
            - ./back/laravel/.env

    nginx:
        image: prostaff.azurecr.io/nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        networks:
            - diplom
        ports:
            - "80:80"
            - "443:443"

    redis.laravel:
        image: prostaff.azurecr.io/redis.laravel:latest
        volumes:
            - './volumes/db/redis/laravel:/data'
        ports:
            - "6379:6379"
        networks:
            - diplom  
            
    certbot:
        image: certbot/certbot
        volumes:
          - ./certbot/conf:/etc/letsencrypt
          - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot  --force-renewal --email projectstaff51@gmail.com --agree-tos --no-eff-email -d househub.pp.ua
        networks:
            - diplom 
    
networks:
    diplom:
        driver: bridge 
