openapi: 3.0.0
info:
  title: User Restore API
  version: 1.0.0
tags:
  - name: userRestore
    description: Endpoints related to restoring user accounts
paths:
  /restore_baby:
    post:
      summary: Restore baby account
      tags:
        - userRestore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id2:
                  type: integer
                  description: Baby ID to be restored
              required:
                - id2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: "Baby account successfully restored."
        '401':
          description: Unauthorized
        '404':
          description: Baby account not found

  /restore_nurse:
    post:
      summary: Restore nurse account
      tags:
        - userRestore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id2:
                  type: integer
                  description: Nurse ID to be restored
              required:
                - id2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: "Nurse account successfully restored."
        '401':
          description: Unauthorized
        '404':
          description: Nurse account not found

  /restore_keeper:
    post:
      summary: Restore keeper account
      tags:
        - userRestore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id2:
                  type: integer
                  description: Keeper ID to be restored
              required:
                - id2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: "Keeper account successfully restored."
        '401':
          description: Unauthorized
        '404':
          description: Keeper account not found

  /restore_client_baby:
    post:
      summary: Restore client baby account
      tags:
        - userRestore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id2:
                  type: integer
                  description: Client Baby ID to be restored
              required:
                - id2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: "Client Baby account successfully restored."
        '401':
          description: Unauthorized
        '404':
          description: Client Baby account not found

  /restore_client_nurse:
    post:
      summary: Restore client nurse account
      tags:
        - userRestore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id2:
                  type: integer
                  description: Client Nurse ID to be restored
              required:
                - id2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: "Client Nurse account successfully restored."
        '401':
          description: Unauthorized
        '404':
          description: Client Nurse account not found

  /restore_client_keeper:
    post:
      summary: Restore client keeper account
      tags:
        - userRestore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id2:
                  type: integer
                  description: Client Keeper ID to be restored
              required:
                - id2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example: "Client Keeper account successfully restored."
        '401':
          description: Unauthorized
        '404':
          description: Client Keeper account not found