openapi: 3.0.0
info:
  version: 1.0.0
  title: Form Age Group API
paths:
  /forms/formagegroups:
    post:
      summary: Add age groups to a form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  form_id:
                    type: string
                    description: Form ID
                  agegroup_id:
                    type: string
                    description: Age Group ID
              required:
                - form_id
                - agegroup_id
              example:
                - form_id: "1"
                  agegroup_id: "2"
                - form_id: "1"
                  agegroup_id: "3"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Age groups successfully added"

  /forms/formagegroups/{id}:
    delete:
      summary: Remove age groups from a form by ID
      parameters:
        - name: id
          in: path
          description: Form ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Age groups successfully removed"