openapi: 3.0.0
info:
  version: 1.0.0
  title: Credential API
paths:
  /forms/credentials:
    get:
      summary: Get all credentials
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  title: "Credential 1"
                  icon: "icon-1"
                - id: 2
                  title: "Credential 2"
                  icon: "icon-2"

    post:
      summary: Create a new credential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Credential title
                icon:
                  type: string
                  description: Credential icon
              required:
                - title
                - icon
              example:
                title: "New Credential"
                icon: "new-icon"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "The credential successfully added"

  /forms/credentials/{id}:
    put:
      summary: Update a credential by ID
      parameters:
        - name: id
          in: path
          description: Credential ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Credential title
                icon:
                  type: string
                  description: Credential icon
              example:
                title: "Updated Credential"
                icon: "updated-icon"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "The credential successfully updated"

    delete:
      summary: Delete a credential by ID
      parameters:
        - name: id
          in: path
          description: Credential ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "The credential successfully deleted"