openapi: 3.0.0
info:
  version: 1.0.0
  title: Form Dutie API
paths:
  /forms/formduties:
    post:
      summary: Add duties to a form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  form_id:
                    type: string
                    description: Form ID
                  dutie_id:
                    type: string
                    description: Dutie ID
              required:
                - form_id
                - dutie_id
              example:
                - form_id: "1"
                  dutie_id: "2"
                - form_id: "1"
                  dutie_id: "3"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Duties successfully added"

  /forms/formduties/{id}:
    delete:
      summary: Remove duties from a form by ID
      parameters:
        - name: id
          in: path
          description: Form ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Duties successfully removed"