openapi: 3.0.0
info:
  version: 1.0.0
  title: Form Education API
paths:
  /forms/formeducations:
    post:
      summary: Add education details to a form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  form_id:
                    type: string
                    description: Form ID
                  education_id:
                    type: string
                    description: Education ID
              required:
                - form_id
                - education_id
              example:
                - form_id: "1"
                  education_id: "2"
                - form_id: "1"
                  education_id: "3"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Education details successfully added"

  /forms/formeducations/{id}:
    delete:
      summary: Remove education details from a form by ID
      parameters:
        - name: id
          in: path
          description: Form ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Education details successfully removed"