openapi: 3.0.0
info:
  version: 1.0.0
  title: Form Nurse Education API
paths:
  /forms/formnurseeducations:
    post:
      summary: Add nurse education details to a form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  form_id:
                    type: string
                    description: Form ID
                  nurseeducation_id:
                    type: string
                    description: Nurse Education ID
              required:
                - form_id
                - nurseeducation_id
              example:
                - form_id: "1"
                  nurseeducation_id: "2"
                - form_id: "1"
                  nurseeducation_id: "3"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Nurse education details successfully added"

  /forms/formnurseeducations/{id}:
    delete:
      summary: Remove nurse education details from a form by ID
      parameters:
        - name: id
          in: path
          description: Form ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Nurse education details successfully removed"