openapi: 3.0.0
info:
  version: 1.0.0
  title: Form Nurse Dutie API
paths:
  /forms/formnurseduties:
    post:
      summary: Add nurse duties details to a form
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  form_id:
                    type: string
                    description: Form ID
                  nursedutie_id:
                    type: string
                    description: Nurse Dutie ID
              required:
                - form_id
                - nursedutie_id
              example:
                - form_id: "1"
                  nursedutie_id: "2"
                - form_id: "1"
                  nursedutie_id: "3"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Nurse duties details successfully added"

  /forms/formnurseduties/{id}:
    delete:
      summary: Remove nurse duties details from a form by ID
      parameters:
        - name: id
          in: path
          description: Form ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Nurse duties details successfully removed"