openapi: 3.0.0
info:
  version: 1.0.0
  title: Watch Worker Nurse API
paths:
  /watchworkernurse:
    get:
      summary: Get the list of watched worker nurses
      parameters:
        - name: data
          in: query
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - user_id: 1
                  anketa_id: 101
                - user_id: 1
                  anketa_id: 102
                # Add more examples if needed

    post:
      summary: Add a worker nurse to the watchlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: User ID
                anketa_id:
                  type: integer
                  description: Worker Nurse ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Анкета добавлена в просмотренные."

    # Add other CRUD operations as needed

  /watchworkernurse/{id}:
    delete:
      summary: Remove a worker nurse from the watchlist
      parameters:
        - name: id
          in: path
          description: ID of the watched worker nurse
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Анкета успешно удалена из просмотра."