openapi: 3.0.0
info:
  version: 1.0.0
  title: Client Keeper API
paths:
  /client/keepers:
    get:
      summary: Get client keepers
      parameters:
        - name: data
          in: query
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                user_id: 1
                confirmed: true
                title_about:
                  en: "About Keeper"
                  ua: "Про смотрителя"
                workperiod_id: 2
                hourpay_id: 3
                monthpay_id: 4
        # Add other response codes as needed

    post:
      summary: Create client keeper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: User ID
                confirmed:
                  type: boolean
                  description: Confirmation status
                title_about:
                  type: object
                  properties:
                    en:
                      type: string
                      description: Title in English
                    ua:
                      type: string
                      description: Title in Ukrainian
                workperiod_id:
                  type: integer
                  description: Work Period ID
                hourpay_id:
                  type: integer
                  description: Hourly Pay ID
                monthpay_id:
                  type: integer
                  description: Monthly Pay ID
              example:
                user_id: 1
                confirmed: true
                title_about:
                  en: "About Keeper"
                  ua: "Про смотрителя"
                workperiod_id: 2
                hourpay_id: 3
                monthpay_id: 4
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                user_id: 1
                confirmed: true
                title_about:
                  en: "About Keeper"
                  ua: "Про смотрителя"
                workperiod_id: 2
                hourpay_id: 3
                monthpay_id: 4
        # Add other response codes as needed

  /client/keepers/{id}:
    put:
      summary: Update client keeper
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title_about:
                  type: object
                  properties:
                    en:
                      type: string
                      description: Title in English
                    ua:
                      type: string
                      description: Title in Ukrainian
                workperiod_id:
                  type: integer
                  description: Work Period ID
                hourpay_id:
                  type: integer
                  description: Hourly Pay ID
                monthpay_id:
                  type: integer
                  description: Monthly Pay ID
              example:
                title_about:
                  en: "Updated About Keeper"
                  ua: "Оновлено Про смотрителя"
                workperiod_id: 5
                hourpay_id: 6
                monthpay_id: 7
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                user_id: 1
                confirmed: true
                title_about:
                  en: "Updated About Keeper"
                  ua: "Оновлено Про смотрителя"
                workperiod_id: 5
                hourpay_id: 6
                monthpay_id: 7
        # Add other response codes as needed

    delete:
      summary: Delete client keeper
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Удаление анкеты прошло успешно."
        # Add other response codes as needed