openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
servers:
  - url: http://laravel.api:8000/
tags:
  - name: auth
    description: Endpoints related to user authentication
paths:
  /login:
    post:
      summary: Authenticate user and get JWT token
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: user@example.com
              password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                access_token: "example_token"
                token_type: "bearer"
                expires_in: 3600
                user: 
                  id: 1
                  name: "Example User"
                  email: "user@example.com"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: "Authentication failed, please try again."

  /me:
    get:
      summary: Get authenticated user information
      tags:
        - auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: 1
                name: "Example User"
                email: "user@example.com"
        '401':
          description: Unauthorized

  /logout:
    post:
      summary: Log out user (Invalidate the token)
      tags:
        - auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                message: "Successfully logged out"
        '401':
          description: Unauthorized

  /refresh:
    post:
      summary: Refresh JWT token
      tags:
        - auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                access_token: "refreshed_token"
                token_type: "bearer"
                expires_in: 3600
        '401':
          description: Unauthorized
